2025-03-20 11:36:24,644 INFO: Microblog startup [in /home/roman/IT/my_progs_directory/Python/new_flask_book/my_app/__init__.py:33]
2025-03-20 11:45:10,495 INFO: Microblog startup [in /home/roman/IT/my_progs_directory/Python/new_flask_book/my_app/__init__.py:33]
2025-03-20 11:45:10,517 INFO: Microblog startup [in /home/roman/IT/my_progs_directory/Python/new_flask_book/my_app/__init__.py:33]
2025-03-20 11:45:10,517 INFO: Microblog startup [in /home/roman/IT/my_progs_directory/Python/new_flask_book/my_app/__init__.py:33]
2025-03-20 12:13:57,397 INFO: Microblog startup [in /home/roman/IT/my_progs_directory/Python/new_flask_book/my_app/__init__.py:33]
2025-03-20 12:14:06,866 INFO: Microblog startup [in /home/roman/IT/my_progs_directory/Python/new_flask_book/my_app/__init__.py:33]
2025-03-20 12:14:14,610 ERROR: Exception on /reset_password_request [GET] [in /home/roman/IT/my_progs_directory/Python/new_flask_book/venv/lib/python3.12/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/home/roman/IT/my_progs_directory/Python/new_flask_book/venv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/roman/IT/my_progs_directory/Python/new_flask_book/venv/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/roman/IT/my_progs_directory/Python/new_flask_book/venv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/roman/IT/my_progs_directory/Python/new_flask_book/venv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/roman/IT/my_progs_directory/Python/new_flask_book/my_app/routes.py", line 97, in reset_password_request
    if form.is_validate_on_submit():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ResetPasswordRequestForm' object has no attribute 'is_validate_on_submit'. Did you mean: 'validate_on_submit'?
2025-03-20 12:14:52,225 INFO: Microblog startup [in /home/roman/IT/my_progs_directory/Python/new_flask_book/my_app/__init__.py:33]
2025-03-20 12:14:56,234 ERROR: Exception on /reset_password_request [GET] [in /home/roman/IT/my_progs_directory/Python/new_flask_book/venv/lib/python3.12/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/home/roman/IT/my_progs_directory/Python/new_flask_book/venv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/roman/IT/my_progs_directory/Python/new_flask_book/venv/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/roman/IT/my_progs_directory/Python/new_flask_book/venv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/roman/IT/my_progs_directory/Python/new_flask_book/venv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/roman/IT/my_progs_directory/Python/new_flask_book/my_app/routes.py", line 103, in reset_password_request
    return render_template('reset_password_request.html', title='Reset Password', form=form)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/roman/IT/my_progs_directory/Python/new_flask_book/venv/lib/python3.12/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/roman/IT/my_progs_directory/Python/new_flask_book/venv/lib/python3.12/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/roman/IT/my_progs_directory/Python/new_flask_book/venv/lib/python3.12/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/roman/IT/my_progs_directory/Python/new_flask_book/venv/lib/python3.12/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/roman/IT/my_progs_directory/Python/new_flask_book/venv/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/roman/IT/my_progs_directory/Python/new_flask_book/venv/lib/python3.12/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/roman/IT/my_progs_directory/Python/new_flask_book/venv/lib/python3.12/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: reset_password_request.html
2025-03-20 12:16:54,844 INFO: Microblog startup [in /home/roman/IT/my_progs_directory/Python/new_flask_book/my_app/__init__.py:33]
2025-03-20 12:17:02,910 ERROR: Exception on /reset_password_request [POST] [in /home/roman/IT/my_progs_directory/Python/new_flask_book/venv/lib/python3.12/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/home/roman/IT/my_progs_directory/Python/new_flask_book/venv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/roman/IT/my_progs_directory/Python/new_flask_book/venv/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/roman/IT/my_progs_directory/Python/new_flask_book/venv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/roman/IT/my_progs_directory/Python/new_flask_book/venv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/roman/IT/my_progs_directory/Python/new_flask_book/my_app/routes.py", line 100, in reset_password_request
    send_password_reset_email(user)
  File "/home/roman/IT/my_progs_directory/Python/new_flask_book/my_app/email.py", line 12, in send_password_reset_email
    token = user.get_reset_password_token()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/roman/IT/my_progs_directory/Python/new_flask_book/my_app/models.py", line 50, in get_reset_password_token
    return jwt.encode({'reset_password': self.id, 'exp': time()+expires_in}, app.config['SECRET_kEY'], algorithm='HS256')
                                                                             ~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'SECRET_kEY'
2025-03-20 12:17:28,073 INFO: Microblog startup [in /home/roman/IT/my_progs_directory/Python/new_flask_book/my_app/__init__.py:33]
2025-03-20 12:17:33,241 ERROR: Exception on /reset_password_request [POST] [in /home/roman/IT/my_progs_directory/Python/new_flask_book/venv/lib/python3.12/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/home/roman/IT/my_progs_directory/Python/new_flask_book/venv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/roman/IT/my_progs_directory/Python/new_flask_book/venv/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/roman/IT/my_progs_directory/Python/new_flask_book/venv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/roman/IT/my_progs_directory/Python/new_flask_book/venv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/roman/IT/my_progs_directory/Python/new_flask_book/my_app/routes.py", line 100, in reset_password_request
    send_password_reset_email(user)
  File "/home/roman/IT/my_progs_directory/Python/new_flask_book/my_app/email.py", line 13, in send_password_reset_email
    send_email('[Microblog] Reset Your Password', sender=app.config['ADMINS'][0], recipients=[user.email],
                                                         ^^^
NameError: name 'app' is not defined
2025-03-20 12:18:46,075 INFO: Microblog startup [in /home/roman/IT/my_progs_directory/Python/new_flask_book/my_app/__init__.py:33]
2025-03-20 12:18:47,952 INFO: Microblog startup [in /home/roman/IT/my_progs_directory/Python/new_flask_book/my_app/__init__.py:33]
2025-03-20 12:19:12,191 INFO: Microblog startup [in /home/roman/IT/my_progs_directory/Python/new_flask_book/my_app/__init__.py:33]
